version: '3'

services:
  bot:
    build: .
    command: ['/bin/sh', '-c', 'while ! pg_isready -h $${POSTGRES_HOST} -p $${POSTGRES_PORT} -U $${POSTGRES_USER}; do sleep 5; done && ./mercanabo']
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - MERCANABO_TOKEN
      - MERCANABO_DEFAULT_TZ
      - MERCANABO_LANG
      - MERCANABO_DEBUG
      - MERCANABO_SUPERADMINS
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql: {}
